# Default fully connected
defaults:
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

# Fourier net
# defaults :
#   - modulus_default
#   - scheduler: tf_exponential_lr
#   - optimizer: adam
#   - loss: sum
#   - _self_

# custom:
#   arch: "FourierNetArch"

scheduler:
  decay_rate: 0.95
  decay_steps: 15000

optimizer: 
  lr: 1e-3

training:
  rec_validation_freq: 1000
  rec_inference_freq: 2000
  rec_monitor_freq: 1000
  rec_results_freq : 1000
  rec_constraint_freq: 2000
  max_steps : 1500000


batch_size:
  inlet: 64
  outlet: 64
  no_slip: 2000
  # interior_lr: 1000
  interior_hr: 3000
  integral_continuity: 64
  num_integral_continuity: 5